name: Deploy Theme
on:
  push:	
    branches:	
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/${{ secrets.GHOST_ADMIN_EMAIL }}
      - uses: TryGhost/${{ secrets.GHOST_ADMIN_EMAIL }}
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
